parameters:
#    nie_credit.example.class: Nie\CreditBundle\Example

services:
#    nie_credit.example:
#        class: %nie_credit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
